{'name': 'Mobikey CRM',
 'version': '19.0.2.2.0',
 'category': 'Sales/CRM',
 'summary': 'Vehicle sales CRM pipeline for Mobikey (KE / UG / TZ)',
 'description': 'CRM qualification with native stage movement. Commercial workflow lives on Sales '
                'quotations.',
 'author': 'Bista Solutions',
 'website': 'https://www.bistasolutions.com',
 'license': 'LGPL-3',
 'depends': ['account', 'sale_crm', 'sale_management', 'sale_stock', 'product', 'mail'],
 'data': ['data/utm_source_data.xml',
          'data/preferred_language_data.xml',
          'data/margin_email_template.xml',
          'data/discount_email_template.xml',
          'data/financing_email_template.xml',
          'data/trade_in_email_template.xml',
          'security/groups.xml',
          'security/ir.model.access.csv',
          'views/crm_lead_views.xml',
          'views/crm_stage_views.xml',
          'views/product_product_view.xml',
          'views/res_config_settings.xml',
          'views/product_template_view.xml',
          'views/sale_order_view.xml',
          'views/mobikey_config_views.xml'],
 'installable': True,
 'application': False,
 'auto_install': False}
